#!/usr/bin/env php
<?php

// dli - DLight command line interface bootstrapper
/*
 * DLight - A lightweight PHP framework for web and CLI applications.
 * 
 * @author Datahihi1
*/

define('ROOT_DIR', __DIR__ . '/');
define('INDEX_DIR', __DIR__ . '/public/');

if (php_sapi_name() !== 'cli') {
	die("This script can only be run from the command line.");
}
if (!file_exists(ROOT_DIR . 'vendor/autoload.php')) {
	die("\033[31mAutoloader not found. Please run 'composer install' in the project root.\033[0m");
}

require_once ROOT_DIR . 'vendor/autoload.php';

use DLight\Application\App;
use DLight\Reports\Report;

Report::setup(true, INDEX_DIR . 'logs/cli.log', Report::cli());

$app = new App();
$app->setUpDliRoutes(ROOT_DIR . "app/Router/command/command.php")
	->bootDli($argv);
